export enum UserRole {
  ADMIN = 'ADMIN',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  SALES_EMPLOYEE = 'SALES_EMPLOYEE',
  WORKSHOP_TECHNICIAN = 'WORKSHOP_TECHNICIAN',
  ACCOUNTANT = 'ACCOUNTANT',
}
